### ISSUE TITLE
Create rpc command to send txs for specified time and amount

### ISSUE THREAD

**Issue by fluffyfunction** [bitcoin-pow/BitcoinPoW#1]
Create rpc command to send txs for specified time and amount.

**Comment by bitcoin-pow** [comment]
Added a new command called 'tx'.
help tx

tx "address" amount ( fee_rate num_sends subtractfeefromamount conf_target "estimate_mode" avoid_reuse verbose )

Send transactions to an address for a BTCW miner to mine with.
Requires wallet passphrase to be set with walletpassphrase call if wallet is encrypted.

Arguments:
1. address                  (string, required) The bitcoin address to send to.
2. amount                   (numeric or string, required) The amount in BTC to send. eg 0.00001
3. fee_rate                 (numeric or string, optional, default=not set, fall back to wallet fee estimation) Specify a fee rate in sat/vB.
4. num_sends                (numeric, optional, default=-1) Confirmation target in blocks
5. subtractfeefromamount    (boolean, optional, default=false) The fee will be deducted from the amount being sent.
                            The recipient will receive less bitcoins than you enter in the amount field.
6. conf_target              (numeric, optional, default=wallet -txconfirmtarget) Confirmation target in blocks
7. estimate_mode            (string, optional, default=unset) The fee estimate mode, must be one of (case insensitive):
                            "unset"
                            "economical"
                            "conservative"
8. avoid_reuse              (boolean, optional, default=true) (only available if avoid_reuse wallet flag is set) Avoid spending from dirty addresses; addresses are considered
                            dirty if they have previously been used in a transaction.
9. verbose                  (boolean, optional, default=false) If true, return extra information about the transaction.

Result (if verbose is not set or set to false):
"hex"    (string) The transaction id.

Result (if verbose is set to true):
{                          (json object)
  "txid" : "hex",          (string) The transaction id.
  "fee reason" : "str"     (string) The transaction fee reason.
}

Examples:

Send BTCW transactions forever with amount of 0.00001, a fee of 700 satoshi/vB, and RBF enabled
> bitcoin-pow-cli tx "191daFa9r8b5UbUD2iuFzqdEEVUcTUFB1S" 0.00001  700

Stop sending BTCW transactions
> bitcoin-pow-cli tx "191daFa9r8b5UbUD2iuFzqdEEVUcTUFB1S" 0.00001  700  0
