### ISSUE TITLE
Block Reindex Error

### ISSUE THREAD

**Issue by carlinhos2008** [bitcoin-pow/BitcoinPoW#14]
Good evening, I noticed an error when you put the reindex=1 command in the bitcoin-pow.conf file, when you reopen the wallet it gives an error in the code, which after that you have to delete the entire blockchain to resynchronize because the wallet stops working. open and it only gives an error, follow the image below of the error
![Error](https://github.com/bitcoin-pow/BitcoinPoW/assets/54419158/30e50497-bc56-4ae3-89cc-f6c4d33813ea)

**Comment by bitcoin-pow** [comment]
Thanks for spending the time to log this.

Branch was created:
https://github.com/bitcoin-pow/BitcoinPoW/tree/14-block-reindex-error

Feel free to look into this and provide a fix for the community. If we can reproduce the issue we'll debug and resolve the issue as well.
