### ISSUE TITLE
SEGWIT (bech32) transactions issue

### ISSUE THREAD

**Issue by wajtecek** [bitcoin-pow/BitcoinPoW#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

I've performed 102 test transactions using SEGWIT type. All was confirmed by the net.
Unfortunately a hashrate doesn't change. Before when I was using LEGIT ones, the hashrate was increased.

I've count transacions before and after sending SEGWIT ones and hashrate is identical with the count of LEGIT transacions.

I think this is unwanted behavior (default type in send tab is SEGWIT in 26.1.0 version).

### Expected behaviour

Sending SEGWIT transations should increase hashrate.

### Steps to reproduce

- check your hashrate
- create some SEGWIT receive channels with bech32 type (default one)
- send transactions to the channels
- after confirmation by the net check your hashrate again

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

26.1.0

### Operating system and version

Linux - use qt

### Machine specifications

4 cores, 8GB RAM, 50GB HDD

**Comment by bitcoin-pow** [comment]
Users can use any address type for sending/receiving BTCW, but specifically for mining, only legacy addresses can be used. In short, if you want to mine, only send to a legacy address.
