### ISSUE TITLE
Wallet: can't open file on MacOS

### ISSUE THREAD

**Issue by iliyaZelenko** [bitcoin-pow/BitcoinPoW#41]
<img width="371" alt="image" src="https://github.com/bitcoin-pow/BitcoinPoW/assets/13103045/1acda9ac-e879-47c5-b756-a007b8ed7f35">

**Comment by bitcoin-pow** [comment]
Give file execute permissions:
chmod +x bitcoin-powd

Now right click on bitcoin-powd and click 'open', wait for the Mac prompt to come and click on 'open'
