### ISSUE TITLE
Mining status error

### ISSUE THREAD

**Issue by bitcoin-pow** [bitcoin-pow/BitcoinPoW#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Enter command getminingstatus between stage1 and stage2 mining. There will be a period where the status back is a json error as shown in the screenshot below:
![mining_status_error](https://github.com/user-attachments/assets/775b7946-e987-4a9e-9dcf-940f389955d5)

### Expected behaviour

Mining status should always be reported without an error.

### Steps to reproduce

1) Start mining
2) issue 'getmininginfo' every second and watch stage0 hash rate.
3) When stage0 hash rate goes to zero, keep sending 'getmininginfo' every second.
4) The json error will appear.
5) After 10 or 20 seconds, the error goes away and 'getmininginfo' works as expected.

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v26.4.3

### Operating system and version

All

**Comment by skylovelian** [comment]
![photo_2024-08-21_22-27-37](https://github.com/user-attachments/assets/de989e61-7418-47e7-b641-d9f0512d3f6d)
An error occurs at the beginning of mining.

**Comment by skylovelian** [comment]
After this problem occurs, mining will stop in the next block.

**Comment by bitcoin-pow** [comment]
Mining does not stop, only the reporting status has the bug. Watch the CPU loading and you will see it is still loaded.

**Comment by bitcoin-pow** [comment]
This was fixed and closed in the following:
https://github.com/bitcoin-pow/BitcoinPoW/issues/62
