### ISSUE TITLE
please get a way to stick on stage 2 without returning to stage 1

### ISSUE THREAD

**Issue by soulistyces** [bitcoin-pow/BitcoinPoW#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

just bounce stage 1 finish then stage 2 after some time max 1 day returns to stage 1 and again the same and again the same never sticks time enouth on stage 2 to find a block, low cpus dont have a chance

### Expected behaviour

bounces back to stage 1 and starts all over again without finding block on stage 2

### Steps to reproduce

just let it mine for 7 days without a block find bouncing between stages

### How did you obtain Bitcoin Core

Pre-built binaries

### What version of Bitcoin Core are you using?

24.5

### Operating system and version

fedora, ubuntu, arch

### Machine specifications

2x ryzen 5 5600 1x ryzen 5 5500u

**Comment by bitcoin-pow** [comment]
The mining algorithm should leave stage2 as soon as the network finds a block. We do not want to be mining stale blocks. This is not an issue. This is how the mining algorithm works.
stage1->stage2->stage1->stage2->stage1->stage2->stage1->stage2....
Blocks can only be found while in stage2.
